.sendoffer {
  /*!
 * Bootstrap v3.3.4 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
  /*! normalize.css v3.0.2 | MIT License | git.io/normalize */
  /*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */
  /*# sourceMappingURL=bootstrap.css.map */
}
.sendoffer textarea {
  height: 200px;
}

.sendoffer-readonly {
  background-color: gray;
}

}
